In [1]:
import numpy as np
a = np.array([1, 2, 3])  # One-dimensional array
b = np.array([[1.5, 2.5], [3.5, 4.5]])  # Two-dimensional array


In [2]:
c = np.array([[1, 2], [3, 4], [5, 6]])
c = c.reshape(2, 3)  # Reshapes c to a 2x3 array

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Elementwise sum, difference, product
print(x + y)  # [5 7 9]
print(x - y)  # [-3 -3 -3]
print(x * y)  # [4 10 18]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))  # Matrix multiplication

[[19 22]
 [43 50]]


In [5]:
x = np.array([[1, 2], [3, 4]])

# Compute the inverse
print(np.linalg.inv(x))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
# Solve the system ax = b
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)
print(x)

[2. 3.]


In [8]:
data = np.array([1, 2, 3, 4, 5])

# Calculate mean, median, and standard deviation
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print(mean, median, std_dev)

3.0 3.0 1.4142135623730951


In [9]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


In [10]:
# Creating a 3D array
z = np.random.rand(2, 3, 4)  # 2x3x4 array with random numbers
print(z)

[[[0.52587419 0.30288669 0.50037786 0.97692273]
  [0.65977242 0.49967761 0.00914506 0.6034636 ]
  [0.65362012 0.68967435 0.41667024 0.75796993]]

 [[0.63341878 0.1038912  0.31786011 0.64657894]
  [0.78933222 0.18664426 0.06957168 0.55678476]
  [0.32714702 0.28639153 0.21337103 0.96699523]]]
